[package]
name = "ordered-dither"
version = "0.1.0"
authors = ["connor.belman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.0"
clap = "2.33.0"